name: Release

on:
  push:
    tags:
      - 'v*'



permissions:
  contents: write

jobs:
  build-release:
    name: Build Release Binary
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install FFmpeg 7 Dependencies
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev clang pkg-config libssl-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/rtsp2flv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-push:
    name: Build & Push Docker Image
    needs: build-release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: peihexian/rtsp2flv

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
